---
name: Build Container Image

on:
  schedule:
    - cron: 0 2 * * 6
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          build-args: INVOICENINJA_VERSION=5-stable
          platforms: linux/amd64,linux/arm64
          tags: ramblurr/invoiceninja:5
